#!/bin/sh

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. ${SCRIPT_DIR}/setupkit.sh.lib
. ${SCRIPT_DIR}/dx.sh.lib

usage_on_help "Starts all services, including a container in which to run your app" "" ${@}
ensure_docker_compose_env

log "🚀" "Starting docker-compose.dx.yml"

docker compose -f docker-compose.dx.yml -p "${PROJECT_NAME}" --env-file ${ENV_FILE} up --build --timestamps --force-recreate

# vim: ft=bash
